### ISSUE TITLE
benchmark page optimization

### ISSUE THREAD

**Issue by nancyzrh** [apache/incubator-shardingsphere-benchmark#12]
1. show performance data for  most recent 30 days
2. show sla performance data

**Comment by nancyzrh** [comment]
3.optimize way of  json data acquisition

**Comment by nancyzrh** [comment]
1.http://shardingsphere.apache.org/benchmark/#/loss_test 
  support for new json data  addition, for example sharding-jdbc
2. http://shardingsphere.apache.org/benchmark/#/encrypt_sharding_test
  if the two data start with different date, should alignment them

**Comment by wqzwh** [comment]
> 1.http://shardingsphere.apache.org/benchmark/#/loss_test
> support for new json data addition, for example sharding-jdbc
> 2. http://shardingsphere.apache.org/benchmark/#/encrypt_sharding_test
> if the two data start with different date, should alignment them

1、Sharding JDBC is not provided for data
2、The data of an object represents a day
![image](https://user-images.githubusercontent.com/16662470/67371490-0ac0cc00-f5af-11e9-8dd1-be6810479f14.png)

**Comment by nancyzrh** [comment]
> > 1.http://shardingsphere.apache.org/benchmark/#/loss_test
> > support for new json data addition, for example sharding-jdbc
> > 2. http://shardingsphere.apache.org/benchmark/#/encrypt_sharding_test
> > if the two data start with different date, should alignment them
> 
> 1、Sharding JDBC is not provided for data
> 2、The data of an object represents a day
> ![image](https://user-images.githubusercontent.com/16662470/67371490-0ac0cc00-f5af-11e9-8dd1-be6810479f14.png)

1. I will add data for test;
2. we should alignment start date

**Comment by wqzwh** [comment]
@nancyzrh  For the second problem, the reason has been found. The modification scheme is tentatively determined to supplement the missing data at the front end.

**Comment by nancyzrh** [comment]
> @nancyzrh For the second problem, the reason has been found. The modification scheme is tentatively determined to supplement the missing data at the front end.

cool~ I have pushed test data for the first problem.

**Comment by wqzwh** [comment]
@nancyzrh the second problem，make only the beginning data

**Comment by wqzwh** [comment]
already completed @nancyzrh

**Comment by wqzwh** [comment]
![image](https://user-images.githubusercontent.com/16662470/67911386-51bb4c80-fbc1-11e9-8faa-57715c4adf6e.png)
