### ISSUE TITLE
Compiling the project fails due to Java file name and public class name conflicts

### ISSUE THREAD

**Issue by xhkyyy** [apache/incubator-shardingsphere-benchmark#26]
Compiling the project fail due to Java file name and public class name conflicts.

**Java file:**

https://github.com/apache/incubator-shardingsphere-benchmark/blob/master/shardingsphere-benchmark/src/main/java/service/util/config/SJDataSourceFactory.java

**Comment by nancyzrh** [comment]
I have fixed thir problem, welcome to pr~
